'type: breaking': ['breaking/*']
'type: feature': ['feature/*', 'features/*', 'feat/*']
'type: improvement': ['improve/*', 'improvement/*', 'improvements/*', 'impr/*']
'type: bugs': ['fix/*', 'fixes/*', 'bug/*', 'bugs/*', 'bugfixes/*']
'type: maintenance': ['maintenance/*']
'type: documentation': ['doc/*', 'docs/*', 'documentation/*', 'documentations/*']
'type: automation': ['automation/*', 'actions/*', 'github/*']
'type: dependencies': ['dependencies/*', 'deps/*']
'type: security': ['security/*']
'type: chore': ['chore/*']

skip-changelog: ['main']
