breaking: ['breaking/*']
feature: ['feature/*', 'features/*', 'feat/*']
improvement: ['improve/*', 'improvement/*', 'improvements/*', 'impr/*']
bugs: ['fix/*', 'fixes/*', 'bug/*', 'bugs/*', 'bugfixes/*']
maintenance: ['maintenance/*']
documentation: ['doc/*', 'docs/*', 'documentation/*', 'documentations/*']
automation: ['automation/*', 'actions/*', 'github/*']
dependencies: ['dependencies/*', 'deps/*']
security: ['security/*']
chore: ['chore/*']

skip-changelog: ['main']
