name: Merge Request Labeler
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
      - uses: TimonVS/pr-labeler-action@v4
